--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 23/04/2022 18:29:33
-- Server version: 10.4.22
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

CREATE DATABASE chatapp
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_general_ci;

--
-- Set default database
--
USE chatapp;

--
-- Create table `users`
--
CREATE TABLE users (
  id VARCHAR(50) NOT NULL DEFAULT '',
  username LONGTEXT NOT NULL,
  password LONGTEXT DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 32768,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `username` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX username USING HASH (username);

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
('42fd44d3-15b0-49b9-852d-4ed19a7188af', 'filipe', '1234');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;